# TensorFlow Basics with Simple Exercises

This notebook introduces TensorFlow basics
## Topics

1. Tensors and tensor shapes  
2. Tensor indexing  
3. Reshaping tensors  
4. TensorFlow variables  
5. Sparse tensors  
6. String tensors  
7. Graphs and functions  
8. Tensor bitwise operations  
9. Numerical operations  


## 0. Setup

TensorFlow 2.x is used throughout the notebook.

If TensorFlow is not installed, uncomment and run the installation line first.

In [1]:
# Run this only when TensorFlow is not already installed.
# !pip install tensorflow

import tensorflow as tf

print("TensorFlow version:", tf.__version__)
print("Eager execution enabled:", tf.executing_eagerly())

TensorFlow version: 2.20.0
Eager execution enabled: True


# 1. Tensors and Tensor Shapes

A tensor is a multidimensional collection of values.

- A scalar has rank 0.
- A vector has rank 1.
- A matrix has rank 2.
- A higher-dimensional tensor has rank 3 or more.

Useful properties and functions:

- `tensor.shape`
- `tensor.dtype`
- `tf.rank(tensor)`
- `tf.size(tensor)`

In [2]:
# Create tensors of different ranks

scalar = tf.constant(5)
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
tensor_3d = tf.constant([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Scalar:", scalar)
print("Vector:", vector)
print("Matrix:\n", matrix)
print("3D tensor:\n", tensor_3d)

Scalar: tf.Tensor(5, shape=(), dtype=int32)
Vector: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Matrix:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
3D tensor:
 tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)


In [3]:
# Check shape, rank, size, and data type

print("Matrix shape:", matrix.shape)
print("Matrix rank:", tf.rank(matrix).numpy())
print("Matrix size:", tf.size(matrix).numpy())
print("Matrix data type:", matrix.dtype)

Matrix shape: (2, 3)
Matrix rank: 2
Matrix size: 6
Matrix data type: <dtype: 'int32'>


In [4]:
# Check the length of each matrix dimension

print("Number of rows:", matrix.shape[0])
print("Number of columns:", matrix.shape[1])

Number of rows: 2
Number of columns: 3


### Exercise 1.1

Create a tensor containing:

```text
10 20 30
40 50 60
```

Print its shape, rank, size, and data type.

In [ ]:
# Write your answer here

# print(...)

# 2. Tensor Indexing

Tensor indexing is similar to indexing Python lists and NumPy arrays.

Common forms:

- `tensor[index]`
- `tensor[start:stop]`
- `tensor[row, column]`
- `tf.slice()`
- `tf.gather()`

In [6]:
# Indexing a 1D tensor

numbers = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])

print("Complete tensor:", numbers.numpy())
print("First element:", numbers[0].numpy())
print("Last element:", numbers[-1].numpy())
print("Elements from index 1 to 3:", numbers[1:4].numpy())
print("Every second element:", numbers[::2].numpy())

Complete tensor: [0 1 2 3 4 5 6 7]
First element: 0
Last element: 7
Elements from index 1 to 3: [1 2 3]
Every second element: [0 2 4 6]


In [7]:
# Indexing a 2D tensor

grid = tf.constant([[0, 1, 2],
                    [3, 4, 5],
                    [6, 7, 8]])

print("Grid:\n", grid.numpy())
print("First row:", grid[0].numpy())
print("Second column:", grid[:, 1].numpy())
print("Second and third columns:\n", grid[:, 1:3].numpy())
print("Element at row 2, column 3:", grid[1, 2].numpy())

Grid:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
First row: [0 1 2]
Second column: [1 4 7]
Second and third columns:
 [[1 2]
 [4 5]
 [7 8]]
Element at row 2, column 3: 5


In [8]:
# Use tf.slice()

slice_result = tf.slice(numbers, begin=[1], size=[3])
print("tf.slice result:", slice_result.numpy())

tf.slice result: [1 2 3]


In [9]:
# Use tf.gather() to select non-consecutive elements

gather_result = tf.gather(numbers, indices=[0, 3, 6])
print("tf.gather result:", gather_result.numpy())

tf.gather result: [0 3 6]


### Exercise 2.1

For the tensor below:

```python
x = tf.constant([10, 20, 30, 40, 50, 60])
```

1. Print the second element.
2. Print the last three elements.
3. Use `tf.gather()` to select `10`, `30`, and `60`.

In [ ]:
x = tf.constant([10, 20, 30, 40, 50, 60])

# Write your answer here

### Exercise 2.2

For the matrix below, print:

1. The second row.
2. The first column.
3. The value `8`.

In [ ]:
x = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# Write your answer here

# 3. Reshaping a Tensor

`tf.reshape()` changes the shape of a tensor without changing its values.

The total number of elements must remain the same.

In [12]:
original = tf.constant([[9, 7, 8],
                        [11, 4, 0]])

print("Original tensor:\n", original.numpy())
print("Original shape:", original.shape)

Original tensor:
 [[ 9  7  8]
 [11  4  0]]
Original shape: (2, 3)


In [13]:
# Reshape 2 × 3 into a 1D tensor with 6 values

one_dimensional = tf.reshape(original, [6])

print("1D tensor:", one_dimensional.numpy())
print("Shape:", one_dimensional.shape)

1D tensor: [ 9  7  8 11  4  0]
Shape: (6,)


In [14]:
# Reshape the same values into 3 rows and 2 columns

three_by_two = tf.reshape(original, [3, 2])

print("3 x 2 tensor:\n", three_by_two.numpy())
print("Shape:", three_by_two.shape)

3 x 2 tensor:
 [[ 9  7]
 [ 8 11]
 [ 4  0]]
Shape: (3, 2)


In [15]:
# Use -1 to let TensorFlow calculate one dimension

automatic_shape = tf.reshape(original, [-1, 1])

print("Automatically calculated shape:\n", automatic_shape.numpy())
print("Shape:", automatic_shape.shape)

Automatically calculated shape:
 [[ 9]
 [ 7]
 [ 8]
 [11]
 [ 4]
 [ 0]]
Shape: (6, 1)


In [16]:
# Transpose swaps rows and columns

transposed = tf.transpose(original)

print("Transposed tensor:\n", transposed.numpy())
print("Shape:", transposed.shape)

Transposed tensor:
 [[ 9 11]
 [ 7  4]
 [ 8  0]]
Shape: (3, 2)


### Exercise 3.1

Create a tensor containing numbers from 1 to 12.

Reshape it into:

1. A `3 × 4` tensor.
2. A `4 × 3` tensor.
3. A one-dimensional tensor.

In [ ]:
values = tf.range(1, 13)

# Write your answer here

# 4. Variables in TensorFlow

A tensor created with `tf.constant()` cannot be changed.

A variable created with `tf.Variable()` can be updated.

Useful methods:

- `assign()`
- `assign_add()`
- `assign_sub()`

In [18]:
# Create a variable

weights = tf.Variable([3, 4])

print("Variable:", weights.numpy())
print("Shape:", weights.shape)
print("Rank:", tf.rank(weights).numpy())
print("Size:", tf.size(weights).numpy())
print("Data type:", weights.dtype)

Variable: [3 4]
Shape: (2,)
Rank: 1
Size: 2
Data type: <dtype: 'int32'>


In [19]:
# Replace one value

weights[1].assign(5)
print("After assign:", weights.numpy())

After assign: [3 5]


In [20]:
# Add and subtract values

weights.assign_add([1, 1])
print("After assign_add:", weights.numpy())

weights.assign_sub([2, 1])
print("After assign_sub:", weights.numpy())

After assign_add: [4 6]
After assign_sub: [2 5]


### Exercise 4.1

Create a variable with value `10`.

1. Change it to `25`.
2. Add `5`.
3. Subtract `10`.

In [ ]:
score = tf.Variable(10)

# Write your answer here

# 5. Sparse Tensors

A sparse tensor contains many zero values.

TensorFlow stores:

- the positions of non-zero values,
- the non-zero values,
- the complete dense shape.

In [22]:
# Create a sparse tensor directly

indices = tf.constant([[1, 2],
                       [3, 3]], dtype=tf.int64)

values = tf.constant([41, 30], dtype=tf.int32)

dense_shape = tf.constant([4, 8], dtype=tf.int64)

sparse_tensor = tf.sparse.SparseTensor(
    indices=indices,
    values=values,
    dense_shape=dense_shape
)

print("Sparse tensor:")
print(sparse_tensor)

Sparse tensor:
SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([41 30], shape=(2,), dtype=int32), dense_shape=tf.Tensor([4 8], shape=(2,), dtype=int64))


In [23]:
# Convert a sparse tensor to a normal dense tensor

dense_version = tf.sparse.to_dense(sparse_tensor)

print("Dense version:\n", dense_version.numpy())

Dense version:
 [[ 0  0  0  0  0  0  0  0]
 [ 0  0 41  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 30  0  0  0  0]]


In [24]:
# Convert a dense tensor to a sparse tensor

dense_tensor = tf.constant([[1, 0, 0],
                            [0, 0, 2],
                            [0, 3, 0]], dtype=tf.float32)

sparse_from_dense = tf.sparse.from_dense(dense_tensor)

print("Dense tensor:\n", dense_tensor.numpy())
print("\nSparse tensor:")
print(sparse_from_dense)

Dense tensor:
 [[1. 0. 0.]
 [0. 0. 2.]
 [0. 3. 0.]]

Sparse tensor:
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]
 [2 1]], shape=(3, 2), dtype=int64), values=tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32), dense_shape=tf.Tensor([3 3], shape=(2,), dtype=int64))


### Exercise 5.1

Convert the following dense tensor into a sparse tensor, then convert it back to a dense tensor.

```text
0 5 0
0 0 0
7 0 9
```

In [ ]:
exercise_dense = tf.constant([[0, 5, 0],
                              [0, 0, 0],
                              [7, 0, 9]])

# Write your answer here

# 6. String Tensors

TensorFlow represents text using the `tf.string` data type.

The `tf.strings` module provides operations such as joining, splitting, changing case, and measuring length.

In [26]:
# Create string tensors

scalar_text = tf.constant("Hello, TensorFlow!")
vector_text = tf.constant(["Hello", "TensorFlow", "World"])
matrix_text = tf.constant([["Hello", "World"],
                           ["TensorFlow", "Rocks"]])

print("Scalar:", scalar_text.numpy())
print("Vector:", vector_text.numpy())
print("Matrix:\n", matrix_text.numpy())

Scalar: b'Hello, TensorFlow!'
Vector: [b'Hello' b'TensorFlow' b'World']
Matrix:
 [[b'Hello' b'World']
 [b'TensorFlow' b'Rocks']]


In [27]:
# Join two strings

first = tf.constant("Hello")
second = tf.constant("World")

joined = tf.strings.join([first, second], separator=" ")
print("Joined:", joined.numpy().decode())

Joined: Hello World


In [28]:
# Split a sentence into words

sentence = tf.constant("Welcome to TensorFlow")
words = tf.strings.split(sentence)

print("Words:", words.numpy())

Words: [b'Welcome' b'to' b'TensorFlow']


In [29]:
# Split a sentence into individual characters

characters = tf.strings.unicode_split(sentence, "UTF-8")

print("First character:", characters[0].numpy().decode())
print("All characters:", characters.numpy())

First character: W
All characters: [b'W' b'e' b'l' b'c' b'o' b'm' b'e' b' ' b't' b'o' b' ' b'T' b'e' b'n'
 b's' b'o' b'r' b'F' b'l' b'o' b'w']


In [30]:
# Other simple string operations

text = tf.constant("TensorFlow Basics")

print("Lowercase:", tf.strings.lower(text).numpy().decode())
print("String length:", tf.strings.length(text).numpy())

Lowercase: tensorflow basics
String length: 17


### Exercise 6.1

Create two string tensors containing your first name and the word `"Student"`.

1. Join them with `" - "` as the separator.
2. Convert the result to lowercase.
3. Print the number of characters.

In [ ]:
name = tf.constant("YourName")
role = tf.constant("Student")

# Write your answer here

# 7. Graphs and Functions in TensorFlow

TensorFlow 2.x uses eager execution by default. This means operations run immediately.

The `@tf.function` decorator converts a Python function into a TensorFlow graph function.

In [32]:
# Eager execution

a = tf.constant(5)
b = tf.constant(6)
c = a * b

print("Result:", c.numpy())
print("Eager execution enabled:", tf.executing_eagerly())

Result: 30
Eager execution enabled: True


In [33]:
# A normal Python function using TensorFlow operations

def multiply_numbers(x, y):
    return x * y

result = multiply_numbers(tf.constant(5), tf.constant(6))
print("Normal function result:", result.numpy())

Normal function result: 30


In [34]:
# Convert the function into a TensorFlow graph function

@tf.function
def graph_multiply(x, y):
    return x * y

result = graph_multiply(tf.constant(5), tf.constant(6))
print("Graph function result:", result.numpy())

Graph function result: 30


In [35]:
# A graph function with more than one operation

@tf.function
def calculate(x, y):
    addition = x + y
    multiplication = x * y
    return addition, multiplication

sum_value, product_value = calculate(
    tf.constant(4),
    tf.constant(3)
)

print("Sum:", sum_value.numpy())
print("Product:", product_value.numpy())

Sum: 7
Product: 12


### Exercise 7.1

Create a `@tf.function` named `square_and_add_one`.

For an input `x`, it should return:

```text
x² + 1
```

Test it using `x = 5`.

In [ ]:
# Write your answer here

# 8. Tensor Bitwise Operations

Bitwise operations work on the binary representation of integer values.

Common operations:

- `tf.bitwise.bitwise_and()`
- `tf.bitwise.bitwise_or()`
- `tf.bitwise.bitwise_xor()`
- `tf.bitwise.left_shift()`
- `tf.bitwise.right_shift()`

In [37]:
tensor1 = tf.constant([5, 3, 7], dtype=tf.int32)
tensor2 = tf.constant([3, 1, 5], dtype=tf.int32)

and_result = tf.bitwise.bitwise_and(tensor1, tensor2)
or_result = tf.bitwise.bitwise_or(tensor1, tensor2)
xor_result = tf.bitwise.bitwise_xor(tensor1, tensor2)

print("Tensor 1:", tensor1.numpy())
print("Tensor 2:", tensor2.numpy())
print("Bitwise AND:", and_result.numpy())
print("Bitwise OR:", or_result.numpy())
print("Bitwise XOR:", xor_result.numpy())

Tensor 1: [5 3 7]
Tensor 2: [3 1 5]
Bitwise AND: [1 1 5]
Bitwise OR: [7 3 7]
Bitwise XOR: [6 2 2]


In [38]:
# Shift bits to the left and right

values = tf.constant([1, 2, 4], dtype=tf.int32)

left_shifted = tf.bitwise.left_shift(values, 1)
right_shifted = tf.bitwise.right_shift(values, 1)

print("Original values:", values.numpy())
print("Left shift by 1:", left_shifted.numpy())
print("Right shift by 1:", right_shifted.numpy())

Original values: [1 2 4]
Left shift by 1: [2 4 8]
Right shift by 1: [0 1 2]


### Exercise 8.1

Use the tensors below to calculate bitwise AND, OR, and XOR.

```python
x = tf.constant([6, 10], dtype=tf.int32)
y = tf.constant([3, 5], dtype=tf.int32)
```

In [ ]:
x = tf.constant([6, 10], dtype=tf.int32)
y = tf.constant([3, 5], dtype=tf.int32)

# Write your answer here

# 9. Numerical Operations in TensorFlow

TensorFlow supports mathematical operations directly on tensors.

Examples include:

- addition,
- subtraction,
- multiplication,
- division,
- minimum and maximum,
- absolute value,
- square and square root,
- sum, mean, and maximum reductions,
- matrix multiplication.

In [40]:
a = tf.constant([3, 3, 3], dtype=tf.float32)
b = tf.constant([2, 2, 2], dtype=tf.float32)

print("Addition:", tf.add(a, b).numpy())
print("Subtraction:", tf.subtract(a, b).numpy())
print("Multiplication:", tf.multiply(a, b).numpy())
print("Division:", tf.divide(a, b).numpy())

Addition: [5. 5. 5.]
Subtraction: [1. 1. 1.]
Multiplication: [6. 6. 6.]
Division: [1.5 1.5 1.5]


In [41]:
x = tf.constant([3, -5, 7], dtype=tf.float32)
y = tf.constant([2, 6, 4], dtype=tf.float32)

print("Minimum:", tf.minimum(x, y).numpy())
print("Maximum:", tf.maximum(x, y).numpy())
print("Absolute value:", tf.abs(x).numpy())
print("Square:", tf.square(x).numpy())
print("Square root of [4, 9, 16]:",
      tf.sqrt(tf.constant([4.0, 9.0, 16.0])).numpy())

Minimum: [ 2. -5.  4.]
Maximum: [3. 6. 7.]
Absolute value: [3. 5. 7.]
Square: [ 9. 25. 49.]
Square root of [4, 9, 16]: [2. 3. 4.]


In [42]:
# Reduction operations

data = tf.constant([[1.0, 2.0, 3.0],
                    [4.0, 5.0, 6.0]])

print("Total sum:", tf.reduce_sum(data).numpy())
print("Mean:", tf.reduce_mean(data).numpy())
print("Maximum:", tf.reduce_max(data).numpy())
print("Column sums:", tf.reduce_sum(data, axis=0).numpy())
print("Row means:", tf.reduce_mean(data, axis=1).numpy())

Total sum: 21.0
Mean: 3.5
Maximum: 6.0
Column sums: [5. 7. 9.]
Row means: [2. 5.]


In [43]:
# Matrix multiplication

matrix_a = tf.constant([[1, 2],
                        [3, 4]])

matrix_b = tf.constant([[5, 6],
                        [7, 8]])

matrix_product = tf.matmul(matrix_a, matrix_b)

print("Matrix product:\n", matrix_product.numpy())

Matrix product:
 [[19 22]
 [43 50]]


### Exercise 9.1

For the tensors below, calculate:

1. Addition
2. Subtraction
3. Element-wise multiplication
4. Division

```python
x = tf.constant([10.0, 20.0, 30.0])
y = tf.constant([2.0, 4.0, 5.0])
```

In [ ]:
x = tf.constant([10.0, 20.0, 30.0])
y = tf.constant([2.0, 4.0, 5.0])

# Write your answer here

### Exercise 9.2

For the matrix below, calculate:

1. The total sum.
2. The mean.
3. The maximum value.
4. The sum of each row.

```python
matrix = tf.constant([[2.0, 4.0],
                      [6.0, 8.0]])
```

In [ ]:
matrix = tf.constant([[2.0, 4.0],
                      [6.0, 8.0]])

# Write your answer here

# Final Practice Exercise

Complete the following steps:

1. Create a tensor containing numbers from 1 to 12.
2. Reshape it into a `3 × 4` matrix.
3. Print the second row.
4. Find the sum of all values.
5. Store the sum in a TensorFlow variable.
6. Add `10` to the variable.

In [ ]:
# Write your complete answer here